name: brn
description: BRN Apps.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  chat_bubbles: ^1.0.0+3
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.2
  expandable: ^5.0.1
  nb_utils: ^4.2.11
  pinput: ^1.2.0
  rating_dialog: ^2.0.0
  youtube_player_flutter: ^8.0.0
  qr_code_scanner: ^0.3.5
  http: ^0.13.3
  flutter_rating_bar: ^4.0.0
  fl_chart: ^0.36.4
  intl: ^0.17.0
  modal_progress_hud: ^0.1.3
  shared_preferences: ^2.0.8
  provider: ^6.0.1
  flutter_nfc_kit: ^3.0.2
  convert: ^3.0.1
  fluttertoast: ^8.0.8
  shimmer: ^2.0.0
  flutter_dropdown_alert: ^1.0.3

  # map
  flutter_map: any
  flutter_map_marker_cluster: any




dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^0.1.2
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4
  lint: ^1.5.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  fonts:
    - family: CustomIcons # the name of your font family
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700

    - family: montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700

  assets:
    - assets/images/

flutter_native_splash:
  color: "#FEFEFE"
  image: assets/images/app_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
